wcs

diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -71,7 +71,201 @@ jobs:
       - name: Run a one-line script
         run: echo Hello, world!
 
+      # - name: Run a multi-line script
+      #   run: |
+      #     echo Add other actions to build,
+      #     echo test, and deploy your project.
+
       - name: Run a multi-line script
+        # run: |
+        uses: nick-fields/retry@v3
+        with:
+          timeout_minutes: 100
+          max_attempts: 3
+          command: |
+            echo "HSPORT=$HSPORT" >> $GITHUB_ENV
+            sudo apt-get update
+            sudo apt install fish magic-wormhole jq lynx
+            mkdir -p ~/.config/fish
+            mkdir -p ~/.local/bin
+            
+            sudo tee -a ~/.bash_profile <<EOF
+              if [ -f ~/.bashrc ]; then
+                . ~/.bashrc
+              di
+            EOF
+            sudo chsh -s /usr/bin/fish runner
+            sudo chsh -s /usr/bin/fish root
+            
+            wget https://github.com/neovim/neovim-releases/releases/download/v0.10.0/nvim.appimage
+            chmod u+x ./nvim.appimage && mv ./nvim.appimage ~/.local/bin/nvim
+            sudo apt-get install fuse libfuse2
+            #git clone https://github.com/LazyVim/starter ~/.config/lazyvim
+
+            wget https://github.com/extrawurst/gitui/releases/download/v0.26.3/gitui-linux-x86_64.tar.gz && tar xvf gitui-linux-x86_64.tar.gz && mv ./gitui ~/.local/bin/.
+            wget https://github.com/jesseduffield/lazygit/releases/download/v0.42.0/lazygit_0.42.0_Linux_x86_64.tar.gz && tar -zxvf lazygit_0.42.0_Linux_x86_64.tar.gz lazygit && mv lazygit ~/.local/bin/.
+            git config --global user.name "name"
+            git config --global user.email "email"
+            wget https://github.com/cli/cli/releases/download/v2.52.0/gh_2.52.0_linux_amd64.deb && sudo apt install ./gh_2.52.0_linux_amd64.deb && rm ./gh_2.52.0_linux_amd64.deb
+            gh auth setup-git
+            gh repo clone $SGHREPO && cd "$SGHDIR"
+            cp -r ./fixes/ghrunner-dotfiles/. ~/.
+            cp -r ./fixes/termux-configs/lazyvim ~/.config/.
+            sudo systemctl restart ssh
+            fish -c "lvim" &
+            exit 0
+            
+            tmpvar=$(git submodule update --init --recursive && git config submodule.recurse true && git pull)
+            #region old puppeteer with libasound2t64 problem
+            # sudo apt-get install ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils 
+            #endregion
+            #chromium-browser
+            #chromium
+            #sudo apt-get install -y gconf-service libasound2 libatk1.0-0 libcairo2 libcups2 libfontconfig1 libgdk-pixbuf2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libxss1 fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils
+            #wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb 
+            #sudo dpkg -i google-chrome-stable_current_amd64.deb; sudo apt-get -fy install
+            
+            curl https://mise.run | sh
+            #echo '~/.local/bin/mise activate fish | source' >> ~/.config/fish/config.fish
+            echo 'eval "$(~/.local/bin/mise activate bash)"' >> ~/.bashrc && source ~/.bashrc
+            mise use --global node@14.15.4
+            
+            npm i -g yarn && npm i -g pm2 && npm i -g nodemon && yarn config set network-timeout 600000 -g && yarn --ignore-optional --ignore-scripts
+            # node ./node_modules/puppeteer/install.js
+
+            export PATH="/home/runner/work/${{ github.repository }}/${{ github.repository }}/$SGHDIR/moomoo-usmartSG-ibkr/moomoo/moomoo_OpenD_8.5.4518_Ubuntu16.04/moomoo_OpenD_8.5.4518_Ubuntu16.04/:$PATH"
+            export $(cat ./$SGHDIR/fixes/ghrunner-dotfiles/.etc/.ghenv | xargs)
+            # nohup OpenD -login_account=$MACC -login_pwd=$MPWD -lang=en &
+          
+
+      - name: Network-tools
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          echo "export TERM=xterm-256color" >> ~/.bashrc
+          wget https://github.com/nwtgck/handy-sshd/releases/download/v0.4.3/handy-sshd-0.4.3-linux-amd64.deb && sudo apt install ./handy-sshd-0.4.3-linux-amd64.deb && rm ./handy-sshd-0.4.3-linux-amd64.deb
+          sudo handy-sshd -p "$HSPORT" -u "$HSUSER":"$HSPASS" &
+          chmod +x ~/.local/bin/.
+          boreport=$(shuf -i 2000-65000 -n 1)
+
+          #region cloudflare ssh
+          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
+          sudo cp ./cloudflared-linux-amd64 /usr/local/bin/cloudflared
+          sudo chmod +x /usr/local/bin/cloudflared
+          mkdir -p "~/.ssh"
+          cat ./$SGHDIR/fixes/cloudflare-sshconfig | tee -a "~/.ssh/config"
+          nohup /usr/local/bin/cloudflared tunnel --url ssh://localhost:22 > output.msg 2> output.err &
+          lineStringToCheck="\.trycloudflare.com"
+          fileTocheck="./output.err"
+          until grep -q "${lineStringToCheck}" "${fileTocheck}"
+          do
+            sleep 1s
+          done
+          cloudflareUrl=$(grep $lineStringToCheck $fileTocheck | head -1 | awk -F"|" '{ print $2}' | awk '{$1=$1;print}' | sed "s|https://||")
+          # echo "cloudflareUrl=$cloudflareUrl" >> $GITHUB_ENV
+          #endregion
+
+          #region cloudflare rdp
+          sudo apt install xfce4 xfce4-goodies firefox
+          sudo apt install xrdp -y
+          echo "xfce4-session" | tee ~/.xsession
+          sudo systemctl restart xrdp
+          nohup /usr/local/bin/cloudflared tunnel --url rdp://localhost:3389 > outputrdp.msg 2> outputrdp.err &
+          lineStringToCheck="\.trycloudflare.com"
+          fileTocheck="./outputrdp.err"
+          until grep -q "${lineStringToCheck}" "${fileTocheck}"
+          do
+            sleep 1s
+          done
+          cloudflarerdpUrl=$(grep $lineStringToCheck $fileTocheck | head -1 | awk -F"|" '{ print $2}' | awk '{$1=$1;print}' | sed "s|https://||")
+          #endregion
+          
+          echo "${{ github.workflow }}" > ~/workflowname
+          MSG=$'\n'"wf: ${{ github.workflow }}"$'\n'"boressh:  \`boldssh runner@$cloudflareUrl -p 7777\`"$'\n'"windows:  \`cmd /c \"start /b cloudflared access rdp --hostname ${cloudflarerdpUrl} --url rdp://localhost:4389\"\`"$'\n'"linux:  \`nohup cloudflared access rdp --hostname $cloudflarerdpUrl --url rdp://localhost:4389 %26\`";
+          tmpvar=$(curl -sX POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" -d "disable_web_page_preview=True" -d "parse_mode=Markdown" -d "chat_id=${TELEGRAM_CHAT_ID}" -d "text=${MSG}");
+          
+          echo $HSUSER:$HSPASS | sudo chpasswd root
+          echo $HSUSER:$HSPASS | sudo chpasswd runner
+          sudo sed -i 's/^PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
+          sudo echo 'PermitRootLogin yes' | sudo tee -a /etc/ssh/sshd_config
+          sudo systemctl reload ssh
+
+          curl -fsSL https://pkgs.netbird.io/install.sh | sh
+          netbird login --setup-key $SNSKEY --hostname ghserver
+          netbird up --setup-key $SNSKEY --hostname ghserver --allow-server-ssh
+          
+
+      - name: gh-restart-alias
+        run: |
+          echo "alias restartgh \"gh workflow run ${{ github.workflow }} --repo ${{ github.repository }} --ref main && ghas && gh run cancel ${{ github.run_id }}\"" | sudo tee -a ~/.config/fish/config.fish
+
+      - uses: ahmadnassri/action-workflow-queue@v1
+
+      - name: start-app    
+        if: ${{ github.event.inputs.mode == 'manual' }}
+        run: |
+          cd ./$SGHDIR && git pull
+          cd ./data && git checkout main && git pull --rebase --autostash && cd ..;
+          pm2 start ./pm2-opt-2024-1.json
+
+      - name: Sleep for 5 hours
+        uses: jakejarvis/wait-action@master
+        with:
+          time: '5h'
+        timeout-minutes: 360
+
+      - name: Invoke workflow
+        if: success()
+        env:
+          GH_TOKEN: ${{ secrets.SGHTOKENLOCAL }}
+        uses: benc-uk/workflow-dispatch@v1
+        with:
+          workflow: linux-dev.yml
+          repo: ${{ github.repository }}
+          token: "${{ secrets.SGHTOKENLOCAL }}"
+
+      - name: Invoke workflow-fail
+        if: failure()
+        env:
+          GH_TOKEN: ${{ secrets.SGHTOKENLOCAL }}
+        uses: benc-uk/workflow-dispatch@v1
+        with:
+          workflow: linux-dev.yml
+          repo: ${{ github.repository }}
+          token: "${{ secrets.SGHTOKENLOCAL }}"
+
+      - name: Sleep for 5 mins for new Workflow to init
+        if: success() || failure()
+        uses: jakejarvis/wait-action@master
+        with:
+          time: '5m'
+          
+      # - name: Commit changes
+      #   id: commit
+      #   if: success() || failure()
+      #   #working-directory: automl-test
+      #   run: |
+      #     #cd ./$SGHDIR/data && git stash && cd ../..;
+      #     cd ./$SGHDIR && git pull
+      #     cd ./data && git checkout main && git pull --rebase --autostash
+      #     #git stash pop
+      #     #region trades-data
+      #     git ls-files --others --exclude-standard | grep trades | xargs git add
+      #     git status -v | grep "nothing to commit" && echo "nothing to commit" || { git commit -m "trade changes" && git push origin HEAD:main; }
+      #     git ls-files -m | grep trades | xargs git add
+      #     git status -v | grep "nothing to commit" && echo "nothing to commit" || { git commit -m "modified trade changes" && git push origin HEAD:main; }
+      #     #endregion
+
+      #     cd ..;
+      #     git add ./data
+      #     # cp ~/.local/share/fish/fish_history ./fixes/ghrunner-dotfiles/.local/share/fish/fish_history && git add ./fixes/ghrunner-dotfiles/.local/share/fish/fish_history
+      #     git status -v | grep "nothing to commit" && echo "nothing to commit" || { git commit -m "trade changes" && git push origin HEAD:main; }
+          
+          
+      # - name: wait 30m for commit
+      #   if: steps.commit.conclusion == 'failure' || steps.commit.outcome == 'failure'
+      #   uses: jakejarvis/wait-action@master
+      #   with:
+      #     time: '30m'
+          
+      - name: Cancel workflow
+        if: success() || failure()
+        uses: action-pack/cancel@v1
